# Generated by Django 5.2.6 on 2025-09-11 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('pot', 'Pot'), ('tag', 'Tag'), ('decoration', 'Decoration'), ('tool', 'Tool'), ('fertilizer', 'Fertilizer')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('planting_date', models.DateField(auto_now_add=True)),
                ('growth_stage', models.CharField(choices=[('seedling', 'Seedling'), ('juvenile', 'Juvenile'), ('mature', 'Mature'), ('flowering', 'Flowering')], default='seedling', max_length=20)),
                ('health', models.IntegerField(default=100)),
                ('last_cared_for', models.DateTimeField(auto_now=True)),
                ('accessories', models.ManyToManyField(blank=True, related_name='plants', to='my_app.accessory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('water', 'Watering'), ('fertilize', 'Fertilizing'), ('prune', 'Pruning'), ('sunlight', 'Sunlight Adjustment')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_actions', to='my_app.plant')),
            ],
        ),
    ]
